language: node_js
node_js:
- 8
stages:
  - lint
  - test
jobs:
  include:
  - stage: lint
    script: npm run linter:js
  - stage: test
    script: npm test -- --coverage --maxWorkers=4
    after_script: cat coverage/lcov.info | node_modules/.bin/coveralls
