#!/usr/bin/env node

const program = require('commander')
const config = require('./package.json')

program
  .version(config.version)
  .command('area', 'generates an area folder with an entry-level React component')
  .command('component', 'generates a React component')
  .parse(process.argv)
